public class Main {
    public static void main(String[] args) {
        System.out.println("Задание 1");
        var dog = 8;
        System.out.println(dog);
        var cat = 3.6;
        System.out.println(cat);
        var paper = 763789;
        System.out.println(paper);
        System.out.println("Задание 2");
        dog = dog + 4;
        System.out.println(dog);
        cat = cat + 4;
        System.out.println(cat);
        paper = paper + 4;
        System.out.println(paper);
        System.out.println("Задание 3");
        dog = dog - 3;
        System.out.println(dog);
        cat = cat - 1.6;
        System.out.println(cat);
        paper = paper - 7639;
        System.out.println(paper);
        System.out.println("Задание 4");
        var friend = 19;
        System.out.println(friend);
        friend = friend + 2;
        System.out.println(friend);
        friend = friend / 7;
        System.out.println(friend);
        System.out.println("Задание 5");
        var frog = 3.5;
        System.out.println(frog);
        frog = frog * 10;
        System.out.println(frog);
        frog = frog / 3.5;
        System.out.println(frog);
        frog = frog + 4;
        System.out.println(frog);
        System.out.println("Задание 6");
        var firstBoxerWeight = 78.2;
        var secondBoxerWeight = 82.7;
        var totalWeight = firstBoxerWeight + secondBoxerWeight;
        System.out.println("Общий вес двух бойцов: " + totalWeight + " кг");
        System.out.println("Задание 7");
        var differenceWeight = firstBoxerWeight - secondBoxerWeight;
        System.out.println("Разница между весами бойцов: " + differenceWeight + " кг");
        differenceWeight = secondBoxerWeight % firstBoxerWeight;
        System.out.println("Разница между весами бойцов: " + differenceWeight + " кг");
        System.out.println("Задание 8");
        var totalWorkHours = 640;
        var timePerWorker = 8;
        var workersCount = totalWorkHours / timePerWorker;
        System.out.println("Всего работников в компании – " + workersCount + " человек");
        var addedWorkerCount = workersCount + 94;
        totalWorkHours = addedWorkerCount * timePerWorker;
        System.out.println("Если в компании работает " + addedWorkerCount + " человека, то всего " + totalWorkHours + " часа работы может быть поделено между сотрудниками");
    }
}